name: Frontend Push Deployment

on:
  push:
    branches: [main]

  production:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Build and Push
        env:
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          REPO: ${{ secrets.REPO }}
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker build -t europe-west1-docker.pkg.dev/$GCLOUD_PROJECT_ID/$REPO/frontend:latest .
          docker push europe-west1-docker.pkg.dev/$GCLOUD_PROJECT_ID/$REPO/frontend:latest

      - name: Deploy
        env:
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          REPO: ${{ secrets.REPO }}
        run: |
          gcloud run deploy task-manager-frontend \
            --region europe-west1 \
            --image=europe-west1-docker.pkg.dev/dev-sphere-410611/demo/frontend \
            --allow-unauthenticated
